## HungerGames
# Revamped by: ShaneBee

# Issues: Please report issues on the GitHub issue tracker @ https://github.com/ShaneBeeTK/HungerGames/issues
# Updates: Can be found on GitHub @ https://github.com/ShaneBeeTK/HungerGames/releases

# More Info: See the wiki for more info on this config @ https://github.com/ShaneBeeTK/HungerGames/wiki/Config.yml

settings:
    spawn-mobs: true
    spawn-mobs-interval: 35
    free-roam: 25
    trackingstick-uses: 8
    players-for-trackingstick: 5
    max-chestcontent: 5
    teleport-at-end: false
    max-team-size: 3
reward:
    enabled: true
    cash: 500
    #Example:     <player> will be replaced by winner
    #commands:
    #  - 'say Hi <player>'
    #  - 'crates key give <player> 1'
    commands:
random-chest:
    enabled: false
    interval: 30
    max-chestcontent: 9
rollback:
    allow-block-break: false
    fix-leaves: true
    prevent-trampling: true
    editable-blocks:
        - GRASS
        - TALL_GRASS
        - GRASS_BLOCK
        - DIRT
        - COBBLESTONE
        - OAK_PLANKS
        - SANDSTONE
        - WHITE_WOOL
        - STONE_BRICKS
        - GLASS_PANE
kits:
    bowman:
        permission: none
        helmet: LEATHER_HELMET color:red
        chestplate: LEATHER_CHESTPLATE color:red
        leggings: LEATHER_LEGGINGS color:red
        boots: LEATHER_BOOTS color:red
        items:
            - BOW name:&2Lucky_Bow
            - ARROW 64 name:&aLucky_Arrow
            - POTION:HEAL:60:0 2 name:&bHealing
        potion-effects:
    survivor:
        permission: none
        helmet: LEATHER_HELMET
        chestplate: LEATHER_CHESTPLATE color:green
        leggings: LEATHER_LEGGINGS color:green
        boots: LEATHER_BOOTS
        items:
            - STONE_SWORD 1 name:&7Survival_Sword
            - BREAD 4 name:&6Peasant's_Bread
            - POTION:HEAL:60:0 2 name:&bHealing
        potion-effects:
    pro:
        permission: none
        helmet: TURTLE_HELMET name:&2Turtle_Shell
        chestplate:
        leggings:
        boots:
        items:
            - IRON_SWORD 1
            - BREAD 4 name:&8Pro_Bread
            - POTION:HEAL:60:1 2 name:&bSuper_Healing
        potion-effects:
    ninja:
        permission: none
        helmet: LEATHER_HELMET color:black
        chestplate: LEATHER_CHESTPLATE color:black name:&7Ninja-Jacket lore:&6Ninja-Stealth-Suit:&4------------- enchant:PROTECTION_FIRE
        leggings: LEATHER_LEGGINGS color:black
        boots: LEATHER_BOOTS color:black enchant:PROTECTION_FALL
        items:
            - POTION:HEAL:60:1 2 name:&bSuper_Healing
        potion-effects:
            - SPEED:1:forever
    stupidclass:
        permission: hg.vip
        helmet:
        chestplate:
        leggings:
        boots:
        items:
            - IRON_SWORD 1 enchant:DAMAGE_ALL:2 enchant:DAMAGE_UNDEAD:2 name:&bOP_&6Sword?
            - BREAD 4
            - POTION:HEAL:60:2 2 name:&bSuper_Duper_Healing
        potion-effects:
            - FIRE_RESISTANCE:2:forever