name: HungerGames
authors: [bob7l, Spoopy, ShaneBee]
description: A Simple, fun, HungerGames plugin
version: 4.1.0
website: https://github.com/ShaneBeeTK/HungerGames
api-version: 1.13
main: me.minebuilders.hg.HG
softdepend: [Multiverse-Core, MultiWorld, Vault, My_Worlds]

commands:
  hg:
    description: HungerGames Base command