name: HungerGames
main: tk.shanebee.hg.HG
authors: [bob7l, Spoopy, ShaneBee]
description: A Simple, fun, HungerGames plugin
version: 4.10.5
website: https://bitbucket.org/ShaneBeeStudios/hungergames
api-version: 1.13
softdepend: [Multiverse-Core, MultiWorld, Vault, My_Worlds, GoldenEnchants]

commands:
  hg:
    description: HungerGames Base command