name: HungerGames
authors: [bob7l, Spoopy, ShaneBee]
description: A Simple, fun, HungerGames plugin
version: 4.0.0-Beta1
api-version: 1.13
main: me.minebuilders.hg.HG
softdepend: [Multiverse-Core, MultiWorld, Vault, My_Worlds]

commands:
  hg:
    description: HungerGames Base command

permissions:
  hg.join:
    description: Permission to join the game using /hg join
    default: true
  hg.leave:
    description: Permission to leave the game using /hg leave
    default: true
  hg.kit:
    description: Permission to get kits using /hg kit <kitname>
    default: true
  hg.listgames:
    description: Permission to see all the available games
    default: true
  hg.list:
    description: Permission to see a list of players in a game
    default: true